####################################################################################################
## Description: Reads in the model draws, fixed effects, and labels generated by pred_draws and then 
##              calculates the draws for a particular chunk of draws (read in by the array job).
##              Also calculates the age-standardized and all-age values.
##              Saves this chunk of draws for all ages/locations/races for each year separately.
##
## Passed args: dir [character] -- home directory for settings and final output
##              sex [integer] -- sex to generate predictions for
##              race [integer] -- race to generate predictions for
##              validate [logical] -- is this a validation model? if so, only mx draws for
##                areas in the validation set are created
##              resub [logical] -- are you resubmitting? if yes, it will not re-save files that already
##                exist (or where the final file with all draws exists)
##              * note that the range of subdraws is read in from an array job
##
## Requires:    prepped data file ("[dir]/data.rds")
##              file specifying areas in the validation set, if validate is T (gs_file)
##              populations (pop_file)
##              age standard file (age_std_file)
##              draws generated by pred_mx ([dir]/initial_sims_[sex]_[race].rds)
##              fixed effects generated by pred_mx ([dir]/fe_sims_[sex]_[race].rds)
##              names of the effects used for subsetting the draws ([dir]/mean_[sex]_[race].rds)
##
## Outputs:     mx draws and estimates, saved in separate files by year and draw "chunk":
##                "[dir]/mx_draws_[area_var]_[year]_[sex]_[race]_[max_subdraw].rds"
##
####################################################################################################

###### Load required libraries
pacman::p_load(R.utils, data.table, Matrix, splines, boot, doParallel, foreach, parallel, TMB)

###### Set up objects from command args
if (!interactive()) {
  (repo <- commandArgs(TRUE)[[1]])
  (output_dir <- commandArgs(TRUE)[[2]])
  (settings_loc <- commandArgs(TRUE)[[3]])
  (sex <- commandArgs(TRUE)[[4]])
  (race <- as.integer(commandArgs(TRUE)[5]))
  (validate <- as.logical(commandArgs(TRUE)[6]))
  (resub <- as.logical(commandArgs(TRUE)[7]))
  (by_sex <- as.logical(commandArgs(TRUE)[8]))
  (output_dir_draws_est <- commandArgs(TRUE)[9])
  (by_source <- commandArgs(TRUE)[[10]])
  (imp <- commandArgs(TRUE)[[11]])
} else {
  sex <- 2
  race <- 99
  validate <- FALSE
  resub <- FALSE
  by_sex <- TRUE
  by_source = TRUE
  imp = 0
}

###### Source functions
funcs <- list.files(paste0(repo, "/functions/"))
for (func in funcs[!funcs %in% "load_sae_shared.R"]) {
  source(paste0(repo, "/functions/", func))
}

###### Assign settings from settings file
get_settings(settings_loc)

set.seed(12345)

if (!exists("by_source")) {
  by_source <- FALSE
}

## Load model fit -------------------------------------------------------------------------
if (is.null(race_together)) race_together <- FALSE

if (race_together) {
  if (by_sex) {
    # read in the model
    out <- readRDS(paste0(output_dir, "/model_fit_", sex, ".rds"))
    mod <- get_params(paste0(output_dir, "/model_fit_", sex, ".rds"))
  } else {
    # read in the model
    out <- readRDS(paste0(output_dir, "/model_fit_0.rds"))
    mod <- get_params(paste0(output_dir, "/model_fit_0.rds"))
  }
} else {
  if (by_sex) {
    # read in the model
    out <- readRDS(paste0(output_dir, "/model_fit_", sex, "_", race, "_", edu, ".rds"))
    mod <- get_params(paste0(output_dir, "/model_fit_", sex, "_", race, "_", edu, ".rds"))
  } else {
    # read in the model
    out <- readRDS(paste0(output_dir, "/model_fit_0.rds"))
    mod <- get_params(paste0(output_dir, "/model_fit_0.rds"))
  }
}

#### Load recode mapping and num vars
recode <- readRDS(paste0(output_dir, "/recode.rds"))

load(paste0(output_dir, "/num_vars.RData"))
load(paste0(output_dir, "/re_graphs.RData")) # used for splines

#### Set gold_standard_source
if (!exists("gold_standard_source")) {
  gold_standard_source <- NULL
}

#### Load prediction frame
if (by_sex) {
  pred_frame <- readRDS(paste0(output_dir, "/pred_frame_", sex, ".rds"))
} else {
  pred_frame <- readRDS(paste0(output_dir, "/pred_frame.rds"))
}

setkeyv(pred_frame, c("area", "state", "year", "sex", "race", "age")[which(c("area", "state", "year", "sex", "race", "age") %in% names(pred_frame))])

#### Load covariates and merge onto pred_frame
if (length(covars) != 0) {
  cov <- readRDS(paste0(output_dir, "/covariates.rds"))
  pred_frame <- merge(pred_frame, cov, by = c("area", "year", "sex", "race", "age"), all.x = TRUE)
  
  ## Standardize covars
  covariates <- readRDS(paste0(output_dir, "/covariates.rds"))
  covars <- names(covariates)[!(names(covariates) %in% c("area", "year", "sex", "age", "race", "level", "state"))]
}

if (!exists("covars_as")) {
  covars_as <- c()
}

if (!exists("covars_re")) {
  covars_re <- c()
}

## read in array arguments
task_id <- ifelse(is.na(as.integer(Sys.getenv("SLURM_ARRAY_TASK_ID"))), 1, as.integer(Sys.getenv("SLURM_ARRAY_TASK_ID")))
if (by_sex) {
  draw_args <- fread(paste0(output_dir_draws_est, "/draw_args_", sex, "_", race, "_", edu, ".csv"))  
} else {
  draw_args <- fread(paste0(output_dir_draws_est, "/draw_args_", race, "_", edu, ".csv"))  
}

## get the draw value
draw_val <- c(draw_args[task_id, start_draw]:draw_args[task_id, end_draw])

# set up source_var argument
# For certain models, we use source_v2 (which separates BRFSS by landline only and combined landline/cellphone samples)
# This argument is used for prediction by-source
if (model %in% paste0("model", c(154))) { # models that use source_v2
  source_var <- "source_v2"
} else{
  source_var <- "source"
}

## get the draw value
if (by_sex) {
  re_file <- paste0(output_dir_draws_est, "/initial_sims_", sex, "_", race, "_", edu, ".rds")
  
  if (!file.exists(re_file)) {
    warning(paste0("File ", re_file, " does not exist!"))
    return(NULL)
  }
  sims <- readRDS(re_file)
  mean <- readRDS(paste0(output_dir_draws_est, "/mean_", sex, "_", race, "_", edu, ".rds"))
} else {
  re_file <- paste0(output_dir_draws_est, "/initial_sims_", race, "_", edu, ".rds")
  
  sims <- readRDS(re_file)
  mean <- readRDS(paste0(output_dir_draws_est, "/mean_", race, "_", edu, ".rds"))
}

sims <- sims[, draw_val]

# the simvars are not actually the draw vals because when the matrices get subset the column numbers change
simvars <- paste0("V", 1:length(draw_val))

# Get spline information, if present in settings.csv
if (!is.null(age_knots_spec)) {
  s_age <- as.data.table(s_age)
}

if (!is.null(year_knots_num)) {
  #  natural spline basis
  if (exists("s_year_ns_no_intercept")) {
    s_year_ns_no_intercept <- as.data.table(s_year_ns_no_intercept)
  }
  
  if (exists("s_year")) {
    s_year <- as.data.table(s_year)
  }
}

if (exists("s_age_ns_no_intercept")) {
  s_age_ns_no_intercept <- as.data.table(s_age_ns_no_intercept)
}

if (model %in% c("model154") | model %like% c("covariate_mod")) {
  # Indicator of whether or not the fixed effects are passed through the  "random" argument in MakeADFun in TMB
  beta_as_random <- FALSE
} else {
  beta_as_random <- TRUE
}

#### Set up list for mean effects and point estimates
point_ests <- list()
if (beta_as_random) {
  fixed <- mod[part == "fixed", -c("id", "part")]
  mod <- mod[part == "random", -c("id", "part")]
} else {
  # if fixed effects are not in the "random" part of the matrix (they normally are "random"
  #   due to the way we typically use MakeADFun), need to grab those from the "fixed" part
  mod <- mod[part == "random" | grepl("B", param), -c("id", "part")]
}

# check that means and sims are the same length
stopifnot(nrow(sims) == length(mean))
# note that "mod" is not necessarily the same length b/c mean includes re#_log_sigma due to how it's constructed in pred script -- not a problem 

# calculate draws for the random portion of the model (differs by model)
if (model %in% c("model113", "model120", "model154")) {
  ##### First deal with the age spline, which all of these models have in common
  
  # Calculate linear predictor ----------------------------------------------
  #### Set up list for mean effects and point estimates
  point_ests <- list()
  
  # calculate draws for the fixed portion of the model
  B_names_all <- names(mean)[grep("^B", names(mean))]
  B_names <- B_names_all[!(B_names_all %in% c("B2_BRFSS", "B2_Gallup", "B2_MarketScan", "B2_mdcr", "B2_HCUP", "B2_NOT_GOLD_SOURCE", "B2_BRFSS_LANDLINE_ONLY", "B3_LANDLINE_ONLY"))] #### Accommodate fixed effects we don't use for pred
  
  # remove B6 and B7 (these are the effects on spline parameters in models 147, 148, 149, ...)
  if (model %in% c("model154")) {
    B_names <- B_names[!grepl("B6|B7", B_names)]
  }
  
  # print out the FE we use for prediction
  print(paste("Predicting out of the following covariates (regardless of 'by_source'):", paste(B_names, collapse = ", ")))
  B <- sims[names(mean) %in% B_names,]
  if (class(B) == "numeric") B <- matrix(B, nrow = 1) else B <- as.matrix(B)
  
  fe <- as.matrix(pred_frame[, c("int", covars, covars_as, covars_re), with = FALSE]) %*% B
  fe_mean <- as.matrix(pred_frame[, c("int", covars, covars_as, covars_re), with = FALSE]) %*% mod[param %in% B_names]$est
  fe_param <- mod[param %in% B_names_all] # even though we don't do prediction from all FE, still want to save
  
  #### Set up fixed effects for model120 if by_source
  if (model %in% c("model120") & by_source) {
    # If so, also need to add to the linear predictor?
    B_names_source <- names(mean)[grep("^B", names(mean))]
    B_names_source <- B_names_source[(B_names_source %in% c("B2_Gallup"))]
    B_source <- sims[names(mean) %in% B_names_source,]
    B_source <- rbind(B_source, c(rep(0, length(draw_val))))
    if (class(B_source)[1] == "numeric") B_source <- matrix(B_source, nrow = 1) else B_source <- as.matrix(B_source)
    fe_source <- cbind(as.data.table(B_source), "source" = c("Gallup", "BRFSS"))
    fe_source <- merge(fe_source, recode$source[, -c("var")], by.x = "source", by.y = "source_index", all.x = TRUE)
    fe_source[, c("source", "source_index_recode") := list(source_index_recode, NULL)]
    setkeyv(fe_source, "source")
    fe <- fe + as.matrix(fe_source[J(pred_frame$source)][, simvars, with = FALSE])
    
    fe_mean <- fe_mean + as.matrix(pred_frame[, as.integer(source == recode$source[source_index == "Gallup", source_index_recode])]) %*% mod[param %in% c("B2_Gallup")]$est
    fe_param <- rbindlist(list(fe_param, mod[param %in% c("B2_Gallup")]), use.names = TRUE, fill = TRUE)
  }
  
  if(source_var == "source_v2" & by_source){
    # get the source (version 2) fixed effects
    B_names_source <- names(mean)[grep("^B", names(mean))]
    B_names_source <- B_names_source[(B_names_source %in% c("B2_Gallup", "B2_BRFSS_LANDLINE_ONLY"))]
    
    # if length B_names_source is zero, then exit from if statement early (nothing to add here)
    if(length(B_names_source) > 0){
      # print the fixed effects we use for prediction because by_source is true
      print(paste("Predicting out of the following covariates (because 'by_source' is TRUE):", paste(B_names_source, collapse = ", ")))
      # get the effects
      B_source <- sims[names(mean) %in% B_names_source,]
      B_source_mean <- mod[param %in% B_names_source,est]
      # add in a row of zeros at the end because effect for BRFSS_LLCP is zero
      B_source <- rbind(B_source, c(rep(0, length(draw_val))))
      B_source_mean <- c(B_source_mean, 0)
      if (class(B_source)[1] == "numeric") B_source <- matrix(B_source, nrow = 1) else B_source <- as.matrix(B_source)
      # add in the source_v2 names/indeces; need to get the same order as the fixed effects
      fe_source <- cbind(as.data.table(B_source), "source_v2" = c(gsub("B2_", "", fe_param$param[grepl("B2_", fe_param$param)]), "BRFSS_LLCP"))
      fe_source_mean <- cbind(as.data.table(list(est = B_source_mean)), "source_v2" = c(gsub("B2_", "", fe_param$param[grepl("B2_", fe_param$param)]), "BRFSS_LLCP"))
      # recode
      fe_source <- merge(fe_source, recode$source_v2[, -c("var")], by.x = "source_v2", by.y = "source_v2_index", all.x = TRUE)
      fe_source_mean <- merge(fe_source_mean, recode$source_v2[, -c("var")], by.x = "source_v2", by.y = "source_v2_index", all.x = TRUE)
      fe_source[, c("source_v2", "source_v2_index_recode") := list(source_v2_index_recode, NULL)]
      fe_source_mean[, c("source_v2", "source_v2_index_recode") := list(source_v2_index_recode, NULL)]
      setkeyv(fe_source, "source_v2")
      setkeyv(fe_source_mean, "source_v2")
      
      # add to the fixed effects
      fe <- fe + as.matrix(fe_source[J(pred_frame$source_v2)][, simvars, with = FALSE])
      fe_mean <- fe_mean + as.matrix(fe_source_mean[J(pred_frame$source_v2)][, est])
      # don't need to update fe_param b/c already saved
    }  
  }
  
  # calculate draws for the random portion of the model (differs by model)
  # For re1: Draws of random effects (structured: RE-levels X number of draws)
  # For re1_mean and re1_param: Mean value of random effects.
  re1 <- data.table(as.matrix(sims[names(mean) == "re1",]))
  re1_mean <- mod[param == "re1"] # For effects collapsed over age and time splines
  re1_param <- mod[param == "re1"] # For effects pre-collapse; reX_param only necessary for random effects splines; re_mean required for all random effects
  
  # get the combinations of age/time spline bases, areas, and races
  combos <- as.data.table(expand.grid(y_spline = seq(1, ncol(s_year)), a_spline = seq(1, ncol(s_age)), area = seq(0, num_j - 1L), race = 1:num_r - 1L))
  
  if (!race_together) {
    combos[, race := get("race", .GlobalEnv)]
  }
  
  re1 <- cbind(re1, combos)
  re1_mean <- cbind(re1_mean, combos)
  re1_param <- cbind(re1_param, combos)
  
  s_age[, age := .I - 1]
  s_year[, year := .I - 1]
  s_year <- melt.data.table(s_year, id.vars = "year", value.name = "y_spline_value", variable.name = "y_spline")
  s_age <- melt.data.table(s_age, id.vars = "age", value.name = "a_spline_value", variable.name = "a_spline")
  
  s_year[, y_spline := as.integer(as.character(y_spline))]
  s_age[, a_spline := as.integer(as.character(a_spline))]
  
  re1 <- merge(re1, s_year, by = "y_spline", allow.cartesian = TRUE)
  re1 <- merge(re1, s_age, by = "a_spline", allow.cartesian = TRUE)
  re1_mean <- merge(re1_mean, s_year, by = "y_spline", allow.cartesian = TRUE)
  re1_mean <- merge(re1_mean, s_age, by = "a_spline", allow.cartesian = TRUE)
  re1_param <- merge(re1_param, s_year, by = "y_spline", allow.cartesian = TRUE)
  re1_param <- merge(re1_param, s_age, by = "a_spline", allow.cartesian = TRUE)
  
  # simvars
  del_vars <- c("y_spline", "y_spline_value", "a_spline", "a_spline_value")
  
  re1 <- re1[, (simvars) := lapply(.SD, function(x) sum(x * y_spline_value * a_spline_value)), .SDcols = simvars, by = c("area", "race", "age", "year")]
  re1 <- re1[, (del_vars) := NULL]
  re1 <- unique(re1)
  setkeyv(re1, c("year", "age", "area", "race"))
  
  re1_mean <- re1_mean[, est := lapply(.SD, function(x) sum(x * y_spline_value * a_spline_value)), .SDcols = c("est"), by = c("area", "race", "age", "year")]
  re1_mean <- re1_mean[, (del_vars) := NULL]
  re1_mean <- unique(re1_mean)
  setkeyv(re1_mean, c("year", "age", "area", "race"))
  
  
  ## Now read in the 2nd random effect
  re2 <- data.table(as.matrix(sims[names(mean) == "re2",]))
  re2_mean <- mod[param == "re2",]
  
  ## Area effect
  re2[, area := 1:num_j - 1L]
  re2_mean[, area := 1:num_j - 1L]
  
  setkeyv(re2, "area")
  setkeyv(re2_mean, "area")
  
  
  ### Now, read in the 3rd random effect
  re3 <- data.table(as.matrix(sims[names(mean) == "re3",]))
  re3_mean <- mod[param == "re3",]
  
  if (model %in% c("model120", "model154")) {
    combos <- as.data.table(expand.grid(age = 0:(num_a - 1), race = 0:(num_r - 1), edu = 0:(num_e - 1), marital = 0:(num_m - 1)))
    if (!race_together) {
      combos[, race := get("race", .GlobalEnv)]
    }
    re3 <- cbind(re3, combos)
    re3_mean <- cbind(re3_mean, combos)
    
    setkeyv(re3, c("age", "race", "edu", "marital"))
    setkeyv(re3_mean, c("age", "race", "edu", "marital"))
  } else {
    combos <- as.data.table(expand.grid(year = 0:(num_t - 1), age = 0:(num_a - 1), race = 0:(num_r - 1), edu = 0:(num_e - 1), marital = 0:(num_m - 1)))
    if (!race_together) {
      combos[, race := get("race", .GlobalEnv)]
    }
    re3 <- cbind(re3, combos)
    re3_mean <- cbind(re3_mean, combos)
    
    setkeyv(re3, c("year", "race", "age", "edu", "marital"))
    setkeyv(re3_mean, c("year", "race", "age", "edu", "marital"))
  }
  
  
  ### Now, read in the 4th random effect
  re4 <- data.table(as.matrix(sims[names(mean) == "re4",]))
  re4_mean <- mod[param == "re4",]
  
  if (model %in% c("model113")) {
    combos <- as.data.table(expand.grid(year = 0:(num_t - 1), age = 0:(num_a - 1), race = 0:(num_r - 1)))
    if (!race_together) {
      combos[, race := get("race", .GlobalEnv)]
    }
    re4 <- cbind(re4, combos)
    re4_mean <- cbind(re4_mean, combos)
    
    setkeyv(re4, c("year", "race", "age"))
    setkeyv(re4_mean, c("year", "race", "age"))
  }
  
  
  ### Now, read in the 5th random effect
  re5 <- data.table(as.matrix(sims[names(mean) == "re5",]))
  re5_mean <- mod[param == "re5",]
  
  ### Data source is the 5th random effect for model49
  if (model %in% c("model113")) {
    re5 <- data.table(as.matrix(sims[names(mean) == "re5",]))
    combos <- as.data.table(expand.grid(state = 0:(num_w - 1), race = 0:(num_r - 1), edu = 0:(num_e - 1), marital = 0:(num_m - 1)))
    if (!race_together) {
      combos[, race := get("race", .GlobalEnv)]
    }
    re5 <- cbind(re5, combos)
    re5_mean <- cbind(re5_mean, combos)
    
    setkeyv(re5, c("race", "state", "edu", "marital"))
    setkeyv(re5_mean, c("race", "state", "edu", "marital"))
  } else if (model %in% c("model120")) {
    if (is.null(gold_standard_source)) stop ("Gold-standard must be specified for this model.")
    
    recode$source_race <- merge(recode$source_race, recode$race[, c("race", "race_recode")], by = "race")
    recode$source_race <- merge(recode$source_race, recode$source[, c("source_index", "source_index_recode")], by.x = "source", by.y = "source_index")
    setkey(recode$source_race, "nrow")
    
    combos <- recode$source_race[, c("nrow", "source_race_recode", "source_index_recode", "race_recode")]
    setnames(combos, c("source_race_recode", "source_index_recode", "race_recode"), c("source_race", "source", "race"))
    
    combos <- merge(combos, as.data.table(expand.grid(source_race = 0:(num_dr - 1L), age = 0:(num_a - 1L))), by = "source_race")
    setkeyv(combos, c("nrow", "age", "race"))
    
    re5 <- cbind(re5, combos)
    re5_mean <- cbind(re5_mean, combos)
    
    combos2 <- as.data.table(expand.grid(race = 0:(num_r - 1L), source = 0:(num_d - 1L), age = 0:(num_a - 1L)))
    re5 <- merge(re5, combos2, by = c("race", "source", "age"), all = TRUE)
    re5_mean <- merge(re5_mean, combos2, by = c("race", "source", "age"), all = TRUE)
    
    re5[is.na(re5)] <- 0
    re5_mean[is.na(re5_mean)] <- 0
    
    setkeyv(re5, c("source", "age", "race"))
    setkeyv(re5_mean, c("source", "age", "race"))
  } else if (model %in% c("model154")) {
    # u5_{dr_v2} 
    if (is.null(gold_standard_source)) stop ("Gold-standard must be specified for this model.")
    
    # estimates for RE5 are only generated for non-gold standard sources and for races
    #   present in the non Gold-standard data, so we create combos based on the DR value rather
    #   than all possible combinations of source and race
    combos <- as.data.table(expand.grid(source_race_v2 = 0:(num_dr_v2 - 1L)))
    stopifnot(re5[, .N] == combos[, .N])
    re5 <- cbind(re5, combos)
    re5_mean <- cbind(re5_mean, combos)
    
    # add the source and race names for each source_race_recode
    re5 <- merge(re5, recode$source_v2_race[, c("source_v2_race_recode", "source_v2", "race")], by.x = c("source_race_v2"), by.y = c("source_v2_race_recode"))
    # add the source_recode values based on the source
    re5 <- merge(re5, recode$source_v2[, c("source_v2_index", "source_v2_index_recode")], by.x = "source_v2", by.y = "source_v2_index")
    # add the race recode values based on the race
    re5 <- merge(re5, recode$race[, c("race", "race_recode")], by.x = "race", by.y = "race")
    re5_mean <- merge(re5_mean, recode$source_v2_race[, c("source_v2_race_recode", "source_v2", "race")], by.x = c("source_race_v2"), by.y = c("source_v2_race_recode"))
    re5_mean <- merge(re5_mean, recode$source_v2[, c("source_v2_index", "source_v2_index_recode")], by.x = "source_v2", by.y = "source_v2_index")
    re5_mean <- merge(re5_mean, recode$race[, c("race", "race_recode")], by.x = "race", by.y = "race")
    
    # keep just the recoded values (e.g., source index, instead of "Gallup" and "BRFSS").
    # These are needed to get the correct ordering
    re5[, c("source_v2", "source_v2_index_recode", "race", "race_recode") := list(source_v2_index_recode, NULL, race_recode, NULL)]
    re5_mean[, c("source_v2", "source_v2_index_recode", "race", "race_recode") := list(source_v2_index_recode, NULL, race_recode, NULL)]
    
    # Now create all combinations of source and race, even if we don't have parameters for each
    #   of those
    combos2 <- as.data.table(expand.grid(race = 0:(num_r - 1L), source_v2 = 0:(num_d_v2 - 1L)))
    # Join with the list of parameters, which will create NAs for source/race/age combos 
    #   that we did not estimate
    re5 <- merge(re5, combos2, by = c("race", "source_v2"), all = TRUE)
    re5_mean <- merge(re5_mean, combos2, by = c("race", "source_v2"), all = TRUE)
    # remove the source_race_v2 column
    re5[, source_race_v2 := NULL]
    re5_mean[, source_race_v2 := NULL]
    
    # Fill those NAs with zeros (they won't contribute to the linear predictor we create
    #   for prediction, therefore RE5 will not have any effect on the predictions for the
    #   gold-standard source by design.)
    re5[is.na(re5)] <- 0
    re5_mean[is.na(re5_mean)] <- 0
    
    setkeyv(re5, c("source_v2", "race"))
    setkeyv(re5_mean, c("source_v2", "race"))
  }
  
  
  ### Now, read in the 6th-8th random effects
  re6 <- data.table(as.matrix(sims[names(mean) == "re6",]))
  re6_mean <- mod[param == "re6",]
  re7_mean <- mod[param == "re7",]
  re8_mean <- mod[param == "re8",]
  
  ### Year, age, and race are the 6th, 7th, and 8th random effects for model120, respectively, and for simplicity are handled together here for this specific model
  if (model %in% c("model120")) {
    re6 <- data.table(as.matrix(sims[names(mean) == "re6",]))
    re6_mean <- mod[param == "re6",]
    re6[, year := 1:num_t - 1L]
    re6_mean[, year := 1:num_t - 1L]
    
    setkeyv(re6, "year")
    setkeyv(re6_mean, "year")
    
    re7 <- data.table(as.matrix(sims[names(mean) == "re7",]))
    re7_mean <- mod[param == "re7",]
    re7[, age := 1:num_a - 1L]
    re7_mean[, age := 1:num_a - 1L]
    
    setkeyv(re7, "age")
    setkeyv(re7_mean, "age")
    
    re8 <- data.table(as.matrix(sims[names(mean) == "re8",]))
    re8_mean <- mod[param == "re8",]
    re8[, race := 1:num_r - 1L]
    re8_mean[, race := 1:num_r - 1L]
    
    setkeyv(re8, "race")
    setkeyv(re8_mean, "race")
  } else if (model %in% c("model154")) {
    # u6_{t'}*s(t), where we use a natural spline basis
    # (note that the only difference between this and what we would do if we had a linear spline is use a different basis function)
    re6 <- data.table(as.matrix(sims[names(mean) == "re6",]))
    re6_mean <- mod[param == "re6",]
    re6_mean[, se := NULL] # remove b/c can't calc SE after collapsing 
    re6_param <- mod[param == "re6",]
    
    # if model 154, we use the same
    #   structural as models 145 and 146, respectively, but we treat the parameters
    #   as fixed effects -- and re6 is called B6 instead
    # Extract the effects for B6, and call them re6 for convienence so we can use
    #   the same linear predictor as in models 145 and 146
    if (model %in% c("model154")) {
      re6 <- data.table(as.matrix(sims[names(mean) == "B6",]))
      re6_mean <- mod[param == "B6",]
      re6_mean[, se := NULL] # remove b/c can't calc SE after collapsing
      re6_param <- mod[param == "B6",]
    }
    
    combos <- as.data.table(list(y_spline = seq(1, ncol(s_year_ns_no_intercept))))
    stopifnot(re6[, .N] == combos[, .N])
    re6 <- cbind(re6, combos)
    re6_mean <- cbind(re6_mean, combos)
    re6_param <- cbind(re6_param, combos)
    
    # construct the value of the spline basis at each year
    s_year_ns_no_intercept[, year := .I - 1]
    s_year_ns_no_intercept <- melt.data.table(s_year_ns_no_intercept, id.vars = "year", value.name = "y_spline_value", variable.name = "y_spline")
    
    s_year_ns_no_intercept[, y_spline := as.integer(as.character(y_spline))]
    
    re6 <- merge(re6, s_year_ns_no_intercept, by = "y_spline", allow.cartesian = TRUE)
    re6_mean <- merge(re6_mean, s_year_ns_no_intercept, by = "y_spline", allow.cartesian = TRUE)
    re6_param <- merge(re6_param, s_year_ns_no_intercept, by = "y_spline", allow.cartesian = TRUE)
    
    del_vars <- c("y_spline", "y_spline_value")
    
    # now compute the value of the effect for each year:
    # Take the estimated parameter for each year basis,
    # multiply it by the weight of the respective year basis for the given year,
    # and then sum these products within each year
    
    re6 <- re6[, (simvars) := lapply(.SD, function(x) sum(x * y_spline_value)), .SDcols = simvars, by = c("year")]
    # now that we've summed across the components, delete the knots/basis values so we can collapse
    re6 <- re6[, (del_vars) := NULL]
    re6 <- unique(re6)
    setkeyv(re6, "year")
    
    # do the same for the mean
    re6_mean <- re6_mean[, est := lapply(.SD, function(x) sum(x * y_spline_value)), .SDcols = "est", by = c("year")]
    re6_mean <- re6_mean[, (del_vars) := NULL]
    re6_mean <- unique(re6_mean)
    setkeyv(re6_mean, "year")
    
    # do not collapse across re6_param
    setkeyv(re6_param, "year")
  }
  
  
  # RE7 
  if (model %in% c("model154")) {
    # u7_{a')*s(a'), where we use a natural spline basis 
    # (note that the only difference between this and what we would do if we had a linear spline is use a different basis function)
    # Same as how we construct re6 above, but for age
    re7 <- data.table(as.matrix(sims[names(mean) == "re7",]))
    re7_mean <- mod[param == "re7",]
    re7_mean[, se := NULL] # remove b/c can't calc SE after collapsing
    re7_param <- mod[param == "re7",]    
    
    # if model 154, we use the same
    #  structural as model 146, but we treat the parameters re7 as a fixed effect
    # Extract the effects for B7, and call them re7 for convienence so we can use
    #   the same linear predictor as in model 146
    if (model %in% c("model154")) {
      re7 <- data.table(as.matrix(sims[names(mean) == "B7",]))
      re7_mean <- mod[param == "B7",]
      re7_mean[, se := NULL] # remove b/c can't calc SE after collapsing
      re7_param <- mod[param == "B7",]
    }
    
    combos <- as.data.table(list(a_spline = seq(1, ncol(s_age_ns_no_intercept))))
    stopifnot(re7[, .N] == combos[, .N])
    re7 <- cbind(re7, combos)
    re7_mean <- cbind(re7_mean, combos)
    re7_param <- cbind(re7_param, combos)
    
    # construct the value of the spline basis at each age
    s_age_ns_no_intercept[, age := .I - 1]
    s_age_ns_no_intercept <- melt.data.table(s_age_ns_no_intercept, id.vars = "age", value.name = "a_spline_value", variable.name = "a_spline")
    s_age_ns_no_intercept[, a_spline := as.integer(as.character(a_spline))]
    
    # combine with params
    re7 <- merge(re7, s_age_ns_no_intercept, by = "a_spline", allow.cartesian = TRUE)
    re7_mean <- merge(re7_mean, s_age_ns_no_intercept, by = "a_spline", allow.cartesian = TRUE)
    re7_param <- merge(re7_param, s_age_ns_no_intercept, by = "a_spline", allow.cartesian = TRUE)
    
    del_vars <- c("a_spline", "a_spline_value")
    
    # now compute the value of the effect for each age:
    # Take the estimated parameter for each age basis,
    # multiply it by the weight of the respective age basis for the given age,
    # and then sum these products within each age
    
    re7 <- re7[, (simvars) := lapply(.SD, function(x) sum(x * a_spline_value)), .SDcols = simvars, by = c("age")]
    # now that we've summed across the components, delete the knots/basis balues so we can collapse
    re7 <- re7[, (del_vars) := NULL]
    re7 <- unique(re7)
    setkeyv(re7, "age")
    
    # do the same for the mean
    re7_mean <- re7_mean[, est := lapply(.SD, function(x) sum(x * a_spline_value)), .SDcols = "est", by = c("age")]
    re7_mean <- re7_mean[, (del_vars) := NULL]
    re7_mean <- unique(re7_mean)
    setkeyv(re7_mean, "age")
    
    # do not collapse across re7_param
    setkeyv(re7_param, "age")
  }
  
  
  # RE8
  if (model %in% c("model154")) {
    # u8_{d2,a|d2 != "BRFSS_LLCP"} -- source (except gold-standard) and age
    re8 <- data.table(as.matrix(sims[names(mean) == "re8",]))
    re8_mean <- mod[param == "re8",]
    
    combos <- as.data.table(expand.grid(age = 0:(num_a - 1L), source_v2_no_gs = 0:(num_d_v2 - 2L))) # -2 because we exclude the gold-standard source
    stopifnot(re8[, .N] == combos[, .N])
    re8 <- cbind(re8, combos)
    re8_mean <- cbind(re8_mean, combos)
    # ggplot(re8_mean, aes(x = age, y = est, color = as.factor(source_v2_no_gs))) + geom_line()
    
    # now, "covert" from source_v2_no_gs to source_v2
    re8 <- merge(re8, recode$source_v2_no_gs[, c("source_v2_no_gs", "source_v2_no_gs_recode")], by.x = "source_v2_no_gs", by.y = "source_v2_no_gs_recode")
    re8_mean <- merge(re8_mean, recode$source_v2_no_gs[, c("source_v2_no_gs", "source_v2_no_gs_recode")], by.x = "source_v2_no_gs", by.y = "source_v2_no_gs_recode")
    
    re8[, `:=`(source_v2_no_gs = source_v2_no_gs.y, source_v2_no_gs.y = NULL)]
    re8_mean[, `:=`(source_v2_no_gs = source_v2_no_gs.y, source_v2_no_gs.y = NULL)]
    
    # we need to expand RE for each source, including the gold-standard source. 
    # fill the values for the gs source with zero
    # In source_v2, gold-standard has index zero. In this RE, we didn't include
    # gold-standard, BRFSS_LANDLINE_ONLY or Gallup is index zero.
    # To recode this to match source_v2 coding AND add row for BRFSS_LLCP,
    # merge re8 with recode$source_v2
    re8 <- merge(re8, recode$source_v2[, c("source_v2_index", "source_v2_index_recode")], by.x = "source_v2_no_gs", by.y = "source_v2_index")[, `:=`(source_v2 = source_v2_index_recode, source_v2_index_recode = NULL, source_v2_no_gs = NULL)]
    re8_mean <- merge(re8_mean, recode$source_v2[, c("source_v2_index", "source_v2_index_recode")], by.x = "source_v2_no_gs", by.y = "source_v2_index")[, `:=`(source_v2 = source_v2_index_recode, source_v2_index_recode = NULL, source_v2_no_gs = NULL)]
    
    # now create all combinations of source and age, even if we don't have parameters for each
    #   of those
    combos2 <- as.data.table(expand.grid(age = 0:(num_a - 1L), source_v2 = 0:(num_d_v2 - 1L)))
    # Join with DT of params (re8), which will create NAs for source/age combos
    #  that we did not estimate
    re8 <- merge(re8, combos2, by = c("age", "source_v2"), all = TRUE)
    re8_mean <- merge(re8_mean, combos2, by = c("age", "source_v2"), all = TRUE)
    
    # Fill those NAs with zeros (they won't contribute to the linear predictor we create)
    re8_mean[is.na(param), param := "re8"]
    re8[is.na(re8)] <- 0
    re8_mean[is.na(re8_mean)] <- 0
    
    # order it by age/source
    setkeyv(re8, c("age", "source_v2"))
    setkeyv(re8_mean, c("age", "source_v2"))
  }
  
  
  # RE9
  re9 <- data.table(as.matrix(sims[names(mean) == "re9",]))
  re9_mean <- mod[param == "re9",]
  if (model %in% c("model120")) {
    ### Year-race-edu-marital is the 9th random effect for model107    
    combos <- as.data.table(expand.grid(year = 0:(num_t - 1), race = 0:(num_r - 1), edu = 0:(num_e - 1), marital = 0:(num_m - 1)))
    if (!race_together) {
      combos[, race := get("race", .GlobalEnv)]
    }
    re9 <- cbind(re9, combos)
    re9_mean <- cbind(re9_mean, combos)
    
    setkeyv(re9, c("year", "race", "edu", "marital"))
    setkeyv(re9_mean, c("year", "race", "edu", "marital"))
  }
  
  
  # RE10
  re10 <- data.table(as.matrix(sims[names(mean) == "re10",]))
  re10_mean <- mod[param == "re10",]
  ### State-race-edu-marital is the 10th random effect for model118
  if (model %in% c("model120")) {
    combos <- as.data.table(expand.grid(state = 0:(num_w - 1), race = 0:(num_r - 1), edu = 0:(num_e - 1), marital = 0:(num_m - 1)))
    if (!race_together) {
      combos[, race := get("race", .GlobalEnv)]
    }
    re10 <- cbind(re10, combos)
    re10_mean <- cbind(re10_mean, combos)
    
    setkeyv(re10, c("race", "state", "edu", "marital"))
    setkeyv(re10_mean, c("race", "state", "edu", "marital"))
  }
  
  
  # Calculate linear predictor ----------------------------------------------
  if (model %in% c("model113")) {
    if (any(ages >= 20)) { # If the age range spans 20
      re <- as.matrix(as.matrix(re1[pred_frame[, list(year, age, area, race)], simvars, with = FALSE]) +
                        as.matrix(re2[pred_frame[, list(area)], simvars, with = FALSE]) +
                        as.matrix(re3[pred_frame[, list(year, race, age, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                        as.matrix(re4[pred_frame[, list(year, race, age)], simvars, with = FALSE]) +
                        as.matrix(re5[pred_frame[, list(race, state, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])))
      
      re_mean <- as.matrix(as.matrix(re1_mean[pred_frame[, list(year, age, area, race)], est]) +
                             as.matrix(re2_mean[pred_frame[, list(area)], est]) +
                             as.matrix(re3_mean[pred_frame[, list(year, race, age, edu, marital)], est] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                             as.matrix(re4_mean[pred_frame[, list(year, race, age)], est]) +
                             as.matrix(re5_mean[pred_frame[, list(race, state, edu, marital)], est] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])))
      re_param <- list("B" = fe_param, "re1" = re1_param, "re2" = re2_mean, "re3" = re3_mean, "re4" = re4_mean, "re5" = re5_mean)
    } else { # Otherwise don't include re3 and re5
      re <- as.matrix(as.matrix(re1[pred_frame[, list(year, age, area, race)], simvars, with = FALSE]) +
                        as.matrix(re2[pred_frame[, list(area)], simvars, with = FALSE]) +
                        as.matrix(re4[pred_frame[, list(year, race, age)], simvars, with = FALSE]))
    }
  } else if (model %in% c("model120")) {
    if (any(ages >= 20)) { # If the age range spans 20
      if (is.null(gold_standard_source) & !by_source) {
        re <- as.matrix(as.matrix(re1[pred_frame[, list(year, age, area, race)], simvars, with = FALSE]) +
                          as.matrix(re2[pred_frame[, list(area)], simvars, with = FALSE]) +
                          as.matrix(re3[pred_frame[, list(age, race, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                          as.matrix(re6[pred_frame[, list(year)], simvars, with = FALSE]) +
                          as.matrix(re7[pred_frame[, list(age)], simvars, with = FALSE]) +
                          as.matrix(re8[pred_frame[, list(race)], simvars, with = FALSE]) +
                          as.matrix(re9[pred_frame[, list(year, race, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                          as.matrix(re10[pred_frame[, list(race, state, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])))
      } else {
        re <- as.matrix(as.matrix(re1[pred_frame[, list(year, age, area, race)], simvars, with = FALSE]) +
                          as.matrix(re2[pred_frame[, list(area)], simvars, with = FALSE]) +
                          as.matrix(re3[pred_frame[, list(age, race, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                          as.matrix(re5[pred_frame[, list(source, age, race)], simvars, with = FALSE]) +
                          as.matrix(re6[pred_frame[, list(year)], simvars, with = FALSE]) +
                          as.matrix(re7[pred_frame[, list(age)], simvars, with = FALSE]) +
                          as.matrix(re8[pred_frame[, list(race)], simvars, with = FALSE]) +
                          as.matrix(re9[pred_frame[, list(year, race, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                          as.matrix(re10[pred_frame[, list(race, state, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])))
        
        re_mean <- as.matrix(as.matrix(re1_mean[pred_frame[, list(year, age, area, race)], est]) +
                               as.matrix(re2_mean[pred_frame[, list(area)], est]) +
                               as.matrix(re3_mean[pred_frame[, list(age, race, edu, marital)], est] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                               as.matrix(re5_mean[pred_frame[, list(source, age, race)], est]) +
                               as.matrix(re6_mean[pred_frame[, list(year)], est]) +
                               as.matrix(re7_mean[pred_frame[, list(age)], est]) +
                               as.matrix(re8_mean[pred_frame[, list(race)], est]) +
                               as.matrix(re9_mean[pred_frame[, list(year, race, edu, marital)], est] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                               as.matrix(re10_mean[pred_frame[, list(race, state, edu, marital)], est] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])))
        
        re_param <- list("B" = fe_param, "re1" = re1_param, "re2" = re2_mean, "re3" = re3_mean, "re5" = re5_mean, "re6" = re6_mean, "re7" = re7_mean, "re8" = re8_mean, "re9" = re9_mean, "re10" = re10_mean)
      }
    } else { # Otherwise don't include re3
      if (is.null(gold_standard_source) & !by_source) {
        re <- as.matrix(as.matrix(re1[pred_frame[, list(year, age, area, race)], simvars, with = FALSE]) +
                          as.matrix(re2[pred_frame[, list(area)], simvars, with = FALSE]) +
                          as.matrix(re6[pred_frame[, list(year)], simvars, with = FALSE]) +
                          as.matrix(re7[pred_frame[, list(age)], simvars, with = FALSE]) +
                          as.matrix(re8[pred_frame[, list(race)], simvars, with = FALSE]))
      } else {
        re <- as.matrix(as.matrix(re1[pred_frame[, list(year, age, area, race)], simvars, with = FALSE]) +
                          as.matrix(re2[pred_frame[, list(area)], simvars, with = FALSE]) +
                          as.matrix(re6[pred_frame[, list(year)], simvars, with = FALSE]) +
                          as.matrix(re7[pred_frame[, list(age)], simvars, with = FALSE]) +
                          as.matrix(re8[pred_frame[, list(race)], simvars, with = FALSE]))
      }
    }
  } else if (model %in% c("model154")) {
    if (any(ages >= 20)) {
      re <- as.matrix(as.matrix(re1[pred_frame[, list(year, age, area, race)], simvars, with = FALSE]) +
                        as.matrix(re2[pred_frame[, list(area)], simvars, with = FALSE]) +
                        as.matrix(re3[pred_frame[, list(age, race, edu, marital)], simvars, with = FALSE] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]]))+
                        as.matrix(re6[pred_frame[, list(year)], simvars, with = FALSE]) +
                        as.matrix(re7[pred_frame[, list(age)], simvars, with = FALSE]))                     
      # create the linear predictor based on above, but using mean est
      re_mean <- as.matrix(as.matrix(re1_mean[pred_frame[, list(year, age, area, race)], est]) +
                             as.matrix(re2_mean[pred_frame[, list(area)], est]) +
                             as.matrix(re3_mean[pred_frame[, list(age, race, edu, marital)], est] * as.integer(pred_frame[, age >= recode$age[age == 20, age_recode]])) +
                             as.matrix(re6_mean[pred_frame[, list(year)], est]) +
                             as.matrix(re7_mean[pred_frame[, list(age)], est]))
      if (by_source) {
        # predict out on RE5
        
        if (model %in% c("model154")) {
          re <- re + as.matrix(as.matrix(re5[pred_frame[, list(source_v2, race)], simvars, with = F])) # model 151 does not have age in RE5
          re_mean <- re_mean + as.matrix(re5_mean[pred_frame[, list(source_v2, race)], est])     
          
          if(model %in% c("model154")){ # also add re8
            re <- re + as.matrix(as.matrix(re8[pred_frame[, list(age, source_v2)], simvars, with = F]))
            re_mean <- re_mean + as.matrix(re8_mean[pred_frame[, list(age, source_v2)], est])
          }
        } else {
          re <- re + as.matrix(as.matrix(re5[pred_frame[, list(source_v2, age, race)], simvars, with = F]))
          re_mean <- re_mean + as.matrix(re5_mean[pred_frame[, list(source_v2, age, race)], est])              
          # note that model 152 has the same re5 and re5_mean structure as the other models, even though the age
          #   term is constructed from a spline
        }
        
      }
      re_param <- list("B" = fe_param, "re1" = re1_param, "re2" = re2_mean, "re3" = re3_mean, "re5" = re5_mean, "re6" = re6_mean, "re7" = re7_mean, "re6_param" = re6_param, "re7_param" = re7_param)
      if(model %in% c("model154")){
        re_param$re8 <- re8_mean
      }
    } else {
      stop("Update model for when any(ages >= 20) is NOT true ")
    }
  }
} else if (model %like% c("covariate_mod")) { #### Covariate models
  #### Set up list for mean effects and point estimates
  point_ests <- list()
  
  # calculate draws for the fixed portion of the model
  B_names <- names(mean)[grep("^B", names(mean))]
  
  B <- sims[names(mean) %in% B_names,]
  if (class(B) == "numeric") B <- matrix(B, nrow = 1) else B <- as.matrix(B)  
  
  fe <- as.matrix(pred_frame[, c("int", covars, covars_as, covars_re), with = FALSE]) %*% B
  fe_mean <- as.matrix(pred_frame[, c("int", covars, covars_as, covars_re), with = FALSE]) %*% mod[param %in% B_names]$est
  fe_param <- mod[param %in% B_names]
  
  ## Area effect
  re1 <- data.table(as.matrix(sims[names(mean) == "re1",]))
  re1_mean <- mod[param == "re1", -c("se")]
  
  re1[, area := 1:num_j - 1L]
  re1_mean[, area := 1:num_j - 1L]
  
  setkeyv(re1, "area")
  setkeyv(re1_mean, "area")
  
  ## Area-time effect
  re2 <- data.table(as.matrix(sims[names(mean) == "re2",]))
  re2_mean <- mod[param == "re2", -c("se")]
  
  # get the combinations of areas and years
  combos <- as.data.table(expand.grid(area = seq(0, num_j - 1L), year = 1:num_t - 1L))
  re2 <- cbind(re2, combos)
  re2_mean <- cbind(re2_mean, combos)
  setkeyv(re2, c("area", "year"))
  setkeyv(re2_mean, c("area", "year"))
  
  ## Area-time-race effect
  re3 <- data.table(as.matrix(sims[names(mean) == "re3",]))
  re3_mean <- mod[param == "re3", -c("se")]
  
  # get the combinations of areas and years
  combos <- as.data.table(expand.grid(area = seq(0, num_j - 1L), year = 1:num_t - 1L, race = 1:num_r - 1L))
  re3 <- cbind(re3, combos)
  re3_mean <- cbind(re3_mean, combos)
  setkeyv(re3, c("area", "year", "race"))
  setkeyv(re3_mean, c("area", "year", "race"))
  
  ## Race effect
  re4 <- data.table(as.matrix(sims[names(mean) == "re4",]))
  re4_mean <- mod[param == "re4", -c("se")]
  
  # get the combinations of races
  combos <- as.data.table(expand.grid(race = 1:num_r - 1L))
  re4 <- cbind(re4, combos)
  re4_mean <- cbind(re4_mean, combos)
  setkeyv(re4, c("race"))
  setkeyv(re4_mean, c("race"))
  
  ## State-race effect
  re5 <- data.table(as.matrix(sims[names(mean) == "re5",]))
  re5_mean <- mod[param == "re5", -c("se")]
  
  # get the combinations of states and races
  combos <- as.data.table(expand.grid(state = seq(0, num_k - 1L), race = 1:num_r - 1L))
  re5 <- cbind(re5, combos)
  re5_mean <- cbind(re5_mean, combos)
  setkeyv(re5, c("state", "race"))
  setkeyv(re5_mean, c("state", "race"))
  
  ## Year-race effect
  re6 <- data.table(as.matrix(sims[names(mean) == "re6",]))
  re6_mean <- mod[param == "re6", -c("se")]
  
  # get the combinations of years and races
  combos <- as.data.table(expand.grid(year = seq(0, num_t - 1L), race = 1:num_r - 1L))
  re6 <- cbind(re6, combos)
  re6_mean <- cbind(re6_mean, combos)
  setkeyv(re6, c("year", "race"))
  setkeyv(re6_mean, c("year", "race"))
  
  ## State-year-race effect
  re7 <- data.table(as.matrix(sims[names(mean) == "re7",]))
  re7_mean <- mod[param == "re7",, -c("se")]
  
  # get the combinations of years and races
  combos <- as.data.table(expand.grid(state = seq(0, num_k - 1L), year = seq(0, num_t - 1L), race = 1:num_r - 1L))
  re7 <- cbind(re7, combos)
  re7_mean <- cbind(re7_mean, combos)
  setkeyv(re7, c("state", "year", "race"))
  setkeyv(re7_mean, c("state", "year", "race"))
  # re7_param <- mod[param == "re7"]
  
  re10 <- data.table(as.matrix(sims[names(mean) == "re10",]))
  re10_mean <- mod[param == "re10", -c("se")] # For effects collapsed over age and time splines
  re10_param <- mod[param == "re10"] # For effects pre-collapse; reX_param only necessary for random effects splines; re_mean required for all random effects
  
  re11 <- data.table(as.matrix(sims[names(mean) == "re11",]))
  re11_mean <- mod[param == "re11", -c("se")] # For effects collapsed over age and time splines
  re11_param <- mod[param == "re11"] # For effects pre-collapse; reX_param only necessary for random effects splines; re_mean required for all random effects
  
  if (model %in% c("covariate_mod15")) {
    # calculate draws for the random portion of the model (differs by model)
    combos <- as.data.table(expand.grid(area = seq(0, num_j - 1L), y_spline = seq(1, ncol(s_year_ns_intercept))))
    
    re11 <- cbind(re11, combos)
    re11_mean <- cbind(re11_mean, combos)
    re11_param <- cbind(re11_param, combos)
    
    s_year_ns_intercept <- as.data.table(s_year_ns_intercept)
    s_year_ns_intercept[, year := .I - 1]
    s_year_ns_intercept <- melt.data.table(s_year_ns_intercept, id.vars = "year", value.name = "y_spline_value", variable.name = "y_spline")
    
    s_year_ns_intercept[, y_spline := as.integer(as.character(y_spline))]
    
    re11 <- merge(re11, s_year_ns_intercept, by = "y_spline", allow.cartesian = TRUE)
    re11_mean <- merge(re11_mean, s_year_ns_intercept, by = "y_spline", allow.cartesian = TRUE)
    re11_param <- merge(re11_param, s_year_ns_intercept, by = "y_spline", allow.cartesian = TRUE)
    
    # simvars
    del_vars <- c("y_spline", "y_spline_value")
    re11 <- re11[, (simvars) := lapply(.SD, function(x) sum(x * y_spline_value)), .SDcols = simvars, by = c("area", "year")]
    re11 <- re11[, (del_vars) := NULL]
    re11 <- unique(re11)
    setkeyv(re11, c("year", "area"))
    
    re11_mean <- re11_mean[, est := lapply(.SD, function(x) sum(x * y_spline_value)), .SDcols = c("est"), by = c("area", "year")]
    re11_mean <- re11_mean[, (del_vars) := NULL]
    re11_mean <- unique(re11_mean)
    setkeyv(re11_mean, c("year", "area"))
  }
  
  re12 <- data.table(as.matrix(sims[names(mean) == "re12",]))
  re12_mean <- mod[param == "re12", -c("se")] # For effects collapsed over age and time splines
  re12_param <- mod[param == "re12"] # For effects pre-collapse; reX_param only necessary for random effects splines; re_mean required for all random effects
  
  # get the combinations of age/time spline bases, areas, and races
  combos <- as.data.table(expand.grid(area = seq(0, num_j - 1L), y_spline = seq(1, ncol(s_year)), race = 1:num_r - 1L))
  
  if (!race_together) {
    combos[, race := get("race", .GlobalEnv)]
  }
  
  re12 <- cbind(re12, combos)
  re12_mean <- cbind(re12_mean, combos)
  re12_param <- cbind(re12_param, combos)
  
  re13 <- data.table(as.matrix(sims[names(mean) == "re13",]))
  re13_mean <- mod[param == "re13", -c("se")] # For effects collapsed over age and time splines
  re13_param <- mod[param == "re13"] # For effects pre-collapse; reX_param only necessary for random effects splines; re_mean required for all random effects
  
  # get the combinations of age/time spline bases, areas, and races
  if (model %in% c("covariate_mod37")) {
    # calculate draws for the random portion of the model (differs by model)
    combos <- as.data.table(expand.grid(area = seq(0, num_j - 1L), y_spline = seq(1, ncol(s_year_ns_intercept)), race = 1:num_r - 1L))
    
    if (!race_together) {
      combos[, race := get("race", .GlobalEnv)]
    }
    
    stopifnot(re13[, .N] == combos[, .N])
    re13 <- cbind(re13, combos)
    re13_mean <- cbind(re13_mean, combos)
    re13_param <- cbind(re13_param, combos)
    
    # s_year_ns_intercept_original <- copy(s_year_ns_intercept)
    s_year_ns_intercept <- as.data.table(s_year_ns_intercept)
    s_year_ns_intercept[, year := .I - 1]
    s_year_ns_intercept <- melt.data.table(s_year_ns_intercept, id.vars = "year", value.name = "y_spline_value", variable.name = "y_spline")
    
    s_year_ns_intercept[, y_spline := as.integer(as.character(y_spline))]
    
    re13 <- merge(re13, s_year_ns_intercept, by = "y_spline", allow.cartesian = TRUE)
    re13_mean <- merge(re13_mean, s_year_ns_intercept, by = "y_spline", allow.cartesian = TRUE)
    re13_param <- merge(re13_param, s_year_ns_intercept, by = "y_spline", allow.cartesian = TRUE)
    
    # simvars
    del_vars <- c("y_spline", "y_spline_value")
    re13 <- re13[, (simvars) := lapply(.SD, function(x) sum(x * y_spline_value)), .SDcols = simvars, by = c("area", "race", "year")]
    re13 <- re13[, (del_vars) := NULL]
    re13 <- unique(re13)
    setkeyv(re13, c("year", "area", "race"))
    
    re13_mean <- re13_mean[, est := lapply(.SD, function(x) sum(x * y_spline_value)), .SDcols = c("est"), by = c("area", "race", "year")]
    re13_mean <- re13_mean[, (del_vars) := NULL]
    re13_mean <- unique(re13_mean)
    setkeyv(re13_mean, c("year", "area", "race"))
  }
  
  re14 <- data.table(as.matrix(sims[names(mean) == "re14",]))
  re14_mean <- mod[param == "re14", -c("se")] # For effects collapsed over age and time splines
  re14_param <- mod[param == "re14"] # For effects pre-collapse; reX_param only necessary for random effects splines; re_mean required for all random effects
  
  # get the combinations of years and races
  combos <- data.table(race = 1:num_r - 1L)
  re14 <- cbind(re14, combos)
  re14_mean <- cbind(re14_mean, combos)
  setkeyv(re14, c("race"))
  setkeyv(re14_mean, c("race"))
  
  ## State-year-race effect
  re15 <- data.table(as.matrix(sims[names(mean) == "re15",]))
  re15_mean <- mod[param == "re15", -c("se")]
  
  # get the combinations of years and races
  combos <- as.data.table(expand.grid(state = seq(0, num_k - 1L), year = seq(0, num_t - 1L), race = 1:num_r - 1L))
  re15 <- cbind(re15, combos)
  re15_mean <- cbind(re15_mean, combos)
  setkeyv(re15, c("state", "year", "race"))
  setkeyv(re15_mean, c("state", "year", "race"))
  
  # natural spline effects on year
  if (model %in% c("covariate_mod7")) {
    re <- as.matrix(as.matrix(re1[pred_frame[, list(area)], simvars, with = FALSE]) +
                      as.matrix(re3[pred_frame[, list(area, year, race)], simvars, with = FALSE]) +
                      as.matrix(re7[pred_frame[, list(state, year, race)], simvars, with = FALSE]))
    
    re_mean <- as.matrix(as.matrix(re1_mean[pred_frame[, list(area)], est]) +
                           as.matrix(re3_mean[pred_frame[, list(area, year, race)], est]) +
                           as.matrix(re7_mean[pred_frame[, list(state, year, race)], est]))
    
    re_param <- list("B" = fe_param, "re1" = re1_mean, "re3" = re3_mean, "re7" = re7_mean)
  } else if (model %in% c("covariate_mod15")) {
    re <- as.matrix(as.matrix(re1[pred_frame[, list(area)], simvars, with = FALSE]) +
                      as.matrix(re11[pred_frame[, list(year, area)], simvars, with = FALSE]))
    
    re_mean <- as.matrix(as.matrix(re1_mean[pred_frame[, list(area)], est]) +
                           as.matrix(re11_mean[pred_frame[, list(year, area)], est]))
    
    re_param <- list("B" = fe_param, "re1" = re1_mean, "re11" = re11_mean)
  } else if (model %in% c("covariate_mod37")) {
    re <- as.matrix(as.matrix(re7[pred_frame[, list(state, year, race)], simvars, with = FALSE]) +
                      as.matrix(re13[pred_frame[, list(year, area, race)], simvars, with = FALSE]))
    
    re_mean <- as.matrix(as.matrix(re7_mean[pred_frame[, list(state, year, race)], est]) +
                           as.matrix(re13_mean[pred_frame[, list(year, area, race)], est]))
    
    re_param <- list("B" = fe_param, "re7" = re7_mean, "re13" = re13_mean)
  }
} else {
  stop("Need to construct linear predictor for ", model)
}

# check there are no NA's -- indicating an issue constructing the linear predictors
stopifnot(length(fe) == length(re))
stopifnot(all(!is.na(fe)))
stopifnot(all(!is.na(re)))

stopifnot(all(!is.na(fe_mean)))
stopifnot(all(!is.na(re_mean)))

# calculate total draws; we recycle the fe object here to reduce memory load
fe <- fe + re
mean_preds <- fe_mean + re_mean

draws <- fe
stopifnot(all(!is.na(draws)))

rm(fe, re); gc()

if (family %in% c("Poisson", "log-gaussian", "poisson") | model %in% c("covariate_mod37")) {
  draws <- data.table(exp(as.matrix(draws)))
  mean_preds <- data.table(exp(mean_preds))
} else if (family == "binomial") {
  draws <- data.table(inv.logit(as.matrix(draws)))
  mean_preds <- data.table(inv.logit(mean_preds))
}

#### Only generate predictions if imp = 0
#### If there are several draw-models/imputations, then predictions should be generated in 
#### combine_imputations to reduce cluster demand rather than for all draw-models/imps

#### Recode pred_frame
pred_frame_recoded <- copy(pred_frame)
pred_frame_recoded$uid <- 1:nrow(pred_frame_recoded)
if (!is.null(pred_frame_recoded$race)) {
  pred_frame_recoded <- merge(pred_frame_recoded, recode$race, by.x = "race", by.y = "race_recode")
  pred_frame_recoded[, c("race", "race.y", "var") := list(race.y, NULL, NULL)]
}
if (!is.null(pred_frame_recoded[["source"]])) {
  pred_frame_recoded <- merge(pred_frame_recoded, recode$source, by.x = "source", by.y = "source_index_recode")
  pred_frame_recoded[, c("source", "var") := list(source_index, NULL)]
}
if(!is.null(pred_frame_recoded[["source_v2"]])){
  pred_frame_recoded <- merge(pred_frame_recoded, recode$source_v2, by.x = "source_v2", by.y = "source_v2_index_recode")
  pred_frame_recoded[, c("source_v2", "source_v2_index", "var") := list(source_v2_index, NULL, NULL)]
}
if (!is.null(pred_frame_recoded$source_race)) { 
  pred_frame_recoded <- merge(pred_frame_recoded, recode$source_race, by.x = "source_race", by.y = "source_race_recode")
  pred_frame_recoded[, c("source", "var") := list(source_index, NULL)]
}
if(!is.null(pred_frame_recoded$source_v2_race)){ 
  pred_frame_recoded <- merge(pred_frame_recoded, recode$source_v2_race, by.x = "source_v2_race", by.y = "source_v2_race_recode")
  pred_frame_recoded[, c("source_v2_race", "var") := list(source_v2_race_recode, NULL)]
}
if (!is.null(pred_frame_recoded$sex)) {
  pred_frame_recoded <- merge(pred_frame_recoded, recode$sex, by.x = "sex", by.y = "sex_recode")
  pred_frame_recoded[, c("sex", "sex.y", "var") := list(sex.y, NULL, NULL)]
}
if (!is.null(pred_frame_recoded$year)) {
  pred_frame_recoded <- merge(pred_frame_recoded, recode$year, by.x = "year", by.y = "year_recode")
  pred_frame_recoded[, c("year", "year.y", "var") := list(year.y, NULL, NULL)]
}
if (!is.null(pred_frame_recoded$age)) {
  pred_frame_recoded <- merge(pred_frame_recoded, recode$age, by.x = "age", by.y = "age_recode")
  pred_frame_recoded[, c("age", "age.y", "var") := list(age.y, NULL, NULL)]
}
if (!is.null(pred_frame_recoded$area)) {
  pred_frame_recoded <- merge(pred_frame_recoded, recode$area, by.x = "area", by.y = "area_recode")
  pred_frame_recoded[, c("area", "mcnty", "var") := list(mcnty, NULL, NULL)]
}
if (!is.null(pred_frame_recoded$state)) {
  pred_frame_recoded <- merge(pred_frame_recoded, recode$state, by.x = "state", by.y = "state_recode")
  pred_frame_recoded[, c("state", "state.y", "var") := list(state.y, NULL, NULL)]
}
if (!is.null(pred_frame_recoded$edu)) {
  if ("edu" %in% colnames(pred_frame_recoded)) {
    pred_frame_recoded <- merge(pred_frame_recoded, recode$edu, by.x = "edu", by.y = "edu_recode")
    pred_frame_recoded[, c("edu", "edu.y", "var") := list(edu.y, NULL, NULL)]
  }
}
if (!is.null(pred_frame_recoded$marital)) {
  if ("marital" %in% colnames(pred_frame_recoded)) {
    pred_frame_recoded <- merge(pred_frame_recoded, recode$marital, by.x = "marital", by.y = "marital_recode")
    pred_frame_recoded[, c("marital", "marital.y", "var") := list(marital.y, NULL, NULL)]
  }
}
# Resort pred_frame_recoded
pred_frame_recoded <- pred_frame_recoded[order(uid)]
pred_frame_recoded[, uid := NULL]

pred_frame_recoded[, int := NULL]
if (length(covars) > 0) {
  pred_frame_recoded[, (covars) := NULL]
}

#### Add pred_frame_recoded to draws
cols <- c("area", "age", "year", "sex", "race", source_var, strat_vars)[which(c("area", "age", "year", "sex", "race", source_var, strat_vars) %in% colnames(pred_frame_recoded))]

draws <- cbind(draws, pred_frame_recoded[, ..cols])
if (exists("mean_preds")) {
  mean_preds <- cbind(mean_preds, pred_frame_recoded[, ..cols])
  setnames(mean_preds, "V1", "est")
}

if (!is.null(strat_vars)) {
  stratpop <- readRDS(paste0(output_dir_draws_est, "/stratpop_", sex, "_", race, "_", edu, ".rds"))
  
  #### Convert factors to integers
  stratpop$age <- as.integer(as.character(stratpop$age))
  
  if ("edu" %in% strat_vars) {
    stratpop$edu <- as.integer(as.character(stratpop$edu))
  }
  if ("marital" %in% strat_vars) {
    stratpop$marital <- as.integer(as.character(stratpop$marital))
  }
  if ("phone" %in% strat_vars) {
    stratpop$phone <- as.integer(as.character(stratpop$phone))
  }
  if ("gq" %in% strat_vars) {
    stratpop$gq <- as.integer(as.character(stratpop$gq))
  }
  
  if (outcome[names(outcome) == names(data_file)[1]] %like% 'overwt') {
    draws_overwt <- copy(draws)
    if (by_sex) {
      for (s in sex) {
        saveRDS(draws_overwt[sex==s], file = paste0(output_dir_draws_est, "/draws/draws_overwt_", area_var, "_", s, "_", edu,"_", max(draw_val), ".rds"))
      }
    } else {
      saveRDS(draws_overwt, file = paste0(output_dir_draws_est, "/draws/draws_overwt_", area_var, "_", edu,"_", max(draw_val), ".rds"))
    }
  } 
  
  if (outcome[names(outcome) == names(data_file)[1]] %like% 'obese') {
    # if "overweight" is in the string draws_overwt, remove it (will be added back on next line)
    if(grepl("overweight", draws_overwt)) draws_overweight <- gsub("overweight", "", draws_overwt)
    output_dir_overwt <- paste0('FILEPATH', draws_overwt, "/imputation", imp, "/draws")
    
    if (by_sex) {
      for (s in sex) {
        draws_overwt <- readRDS(paste0(output_dir_overwt, "/draws_overwt_", area_var, "_", s, "_", edu, "_", max(draw_val), ".rds"))
      }
    } else {
      draws_overwt <- readRDS(paste0(output_dir_overwt, "/draws_overwt_", area_var, "_", edu, "_", max(draw_val), ".rds"))
    }
    
    key_by_draws <- c("area", "year", "sex", "age", "race", strat_vars)
    # add source or source_v2 to key_by if by_source
    if(by_source){
      key_by_draws <- c(key_by_draws, source_var)
    }
    setkeyv(draws_overwt, key_by_draws)
    setkeyv(draws, key_by_draws)
    
    for (ss in 1:draw_width) {
      print(ss)
      col <- paste0("V", ss)
      setnames(draws, paste0("V", ss), 'col')
      draws$col <- draws$col*draws_overwt[, ..col]
      setnames(draws, 'col', paste0("V", ss))
    }
  } 
  
  #### Merge post-stratification weights onto draws
  draws <- merge(draws, stratpop, by.x = c("area", "age", "year", "sex", "race", strat_vars), 
                 by.y = c("mcnty", "age", "year", "sex", "race", strat_vars), all.x = TRUE)
  
  #### Collapse by post-stratification vars
  draws_agg <- list()
  for (ss in 1:draw_width) {
    print(ss)
    col <- paste0("V", ss)
    if (by_source) {
      draws_agg[[ss]] <- draws[, list(sim = ss, pred = weighted.mean(get(col), value, na.rm = TRUE)), by = c("area", "year", "sex", "age", "race", source_var)]  
    } else {
      draws_agg[[ss]] <- draws[, list(sim = ss, pred = weighted.mean(get(col), value, na.rm = TRUE)), by = c("area", "year", "sex", "age", "race")]  
    }
  }
  draws <- rbindlist(draws_agg)
  
  #### dcast back to wide
  if (by_source) {
    draws_formula <- paste("area + year + sex + age + race +", source_var, "~ sim")
    draws <- dcast(draws, as.formula(draws_formula), value.var = "pred")
  } else {
    draws <- dcast(draws, area + year + sex + age + race ~ sim, value.var = "pred") 
  }
}

## Split out draws by year, calculate all-ages, age-standardized draws, collapse draws, and save ---
# load and subset the population file, then merge onto draws
if (file.exists(paste0(output_dir_draws_est, "/population.rds"))) {
  pop <- readRDS(paste0(output_dir_draws_est, "/population.rds"))
} else {
  pop <- readRDS(pop_file)
}

popage <- unique(as.character(pop$age))

if (max(popage) != max(as.character(ages)) &
    max(head(popage, -1)) == max(as.character(ages))) {
  pop[, age := ifelse(age == max(popage), max(ages), as.character(age))]
  pop <- pop[, list(pop = sum(pop)), by = c(area_var, "year", "sex", "age", "race", "state")]
  pop[, age := as.integer(as.character(age))]
}

if (!by_race) {
  pop[, race := 1]
}

if (!("age" %in% colnames(draws))) {
  draws$joiner <- 1
  age_table <- data.table("age" = ages, "joiner" = 1)
  draws <- merge(draws, age_table, by = "joiner", allow.cartesian = TRUE)
}

if (!("sex" %in% colnames(draws))) {
  draws$joiner <- 1
  sex_table <- data.table("sex" = sexes, "joiner" = 1)
  draws <- merge(draws, sex_table, by = "joiner", allow.cartesian = TRUE)
}

if (race_together) {
  if (by_sex) {
    pop <- pop[sex == get("sex", .GlobalEnv) & age %in% get("ages", .GlobalEnv), list(pop = sum(pop)), by = c(area_var, "year", "age", "race")]
    merge_vars <- c("area", "year", "age")
  } else {
    merge_vars <- c("area", "year", "age", "sex", "race")[which(c("area", "year", "age", "sex", "race") %in% colnames(draws))]
    merge_vars[merge_vars == "area"] <- "mcnty"
    pop <- pop[age %in% get("ages", .GlobalEnv), .(pop = sum(pop)), by = c(merge_vars)] # FIXME
    merge_vars[merge_vars == "mcnty"] <- "area"
  }
  merge_vars <- c(merge_vars, "race")
} else {
  if (by_sex) {
    pop <- pop[race == get("race", .GlobalEnv) & sex == get("sex", .GlobalEnv) & age %in% get("ages", .GlobalEnv),
               list(pop = sum(pop)), by = c(area_var, "year", "age")]
    merge_vars <- c("area", "year", "age")
  } else {
    pop <- pop[race == get("race", .GlobalEnv) & age %in% get("ages", .GlobalEnv),
               list(pop = sum(pop)), by = c(area_var, "year", "age", "sex")]
    merge_vars <- c("area", "year", "age", "sex")
  }
}

setnames(pop, area_var, "area")
draws <- merge(draws, pop, by = merge_vars, all.x = TRUE)
draws$joiner <- NULL

# No missing values are expected
stopifnot(!any(is.na(draws[, -c("pop")])))

# load the age standard
std_wt <- readRDS(age_std_file)[, list(age, wt = wt / sum(wt))]

if (draw_val[1] == 1) { # Only need to save these once, total
  # Save mean preds and params
  saveRDS(re_mean, file = paste0(output_dir_draws_est, "/re_mean_", sex, ".rds"))
  saveRDS(re_param, file = paste0(output_dir_draws_est, "/re_param_", sex, ".rds"))
} 
# Save mean preds
if (exists("mean_preds")) {
  saveRDS(mean_preds, file = paste0(output_dir_draws_est, "/mean_preds_", sex, ".rds"))
}

# split up data and process separately by year
all_draws <- draws
rm(draws)

all_draws <- lapply(years, function(this_year) all_draws[year == this_year,])
for (this_year in years) {
  cat(paste(Sys.time(), this_year, "\n"))
  draws <- all_draws[[which(years == this_year)]]
  draws[, level := area_var]
  
  if (by_source) {
    draws <- melt(draws, id.vars = c("level", "area", "year", "sex", "race", "age", source_var, "pop"), variable.name = "sim", value.name = "pred")  
  } else {
    draws <- melt(draws, id.vars = c("level", "area", "year", "sex", "race", "age", "pop")[which(c("level", "area", "year", "sex", "race", "age", "pop") %in% colnames(draws))], variable.name = "sim", value.name = "pred")
  }
  
  draws[, sim := as.integer(sim)]
  
  # re-code the draws to correspond to draw_val
  if (n.imp > 1) { # if running multiple imputations
    draws[, sim := sim + n.imp * (min(draw_val) - 1)]
  } else {
    draws[, sim := sim + (min(draw_val) - 1)]
  }
  
  # specify the columns by which to summarize/aggregate/etc since now we have both adjusted and unadjusted points
  merge_vars <- c("level", "area", "year", "sex", "race", "sim")  
  if (by_source) {
    merge_vars <- c(merge_vars, source_var)
  }
  
  # add all-ages rates
  draws <- calc_all_ages(draws, std_wt, "pred", merge_vars)
  
  # save draws and estimates
  if (race_together) {
    for (r in races) {
      message(r)
      if (by_sex) {
        saveRDS(draws[race == r], file = paste0(output_dir_draws_est, "/draws/draws_", area_var, "_", this_year, "_", sex, "_", r, "_", edu,"_", 
                                                max(draw_val), ".rds"))
      } else {
        for (s in 1:2) {
          saveRDS(draws[race == r & sex == s], file = paste0(output_dir_draws_est, "/draws/draws_", area_var, "_", this_year, "_", s, "_", r, "_", edu,"_", 
                                                             max(draw_val), ".rds"))
        }
      }
    }
  } else {
    saveRDS(draws, file = paste0(output_dir_draws_est, "/draws/draws_", area_var, "_", this_year, "_", sex, "_", race, "_", edu,"_", 
                                 max(draw_val), ".rds"))
  }
  
  all_draws[[which(years == this_year)]] <- NA
  rm(draws); gc()
}
